### ISSUE TITLE
Conflict when installing resource-locker-operator with other redhat-cop operators ?

### ISSUE THREAD

**Issue by aelbarkani** [redhat-cop/resource-locker-operator#44]
I've noticed that having this operator installed with other redhat-cop operators likehttps://github.com/redhat-cop/cert-utils-operator in the same cluster is causing problems to OLM. The other operators seems to be stuck in Pending state.
Maybe because the SA used is default ? I've noticed that this issue doesn't happen anymore with https://github.com/redhat-cop/namespace-configuration-operator since some days ago they have changed the SA name.

https://github.com/redhat-cop/cert-utils-operator/issues/88

**Comment by raffaelespazzoli** [comment]
this should be resolved by #43 , this fix has been released yesterday, please let me know if it solved it for you.

**Comment by raffaelespazzoli** [comment]
closed by #43
