### ISSUE TITLE
Can't install the operator on Kubernetes without PrometheusOperator even though "enableMonitoring=false"

### ISSUE THREAD

**Issue by Obirah** [redhat-cop/resource-locker-operator#54]
Hi,

I'm trying to install the resource-locker-operator with Helm on an AWS EKS cluster that has no PrometheusOperator.

I'm using the following command: `helm upgrade resource-locker-operator resource-locker-operator/resource-locker-operator --install --set enableMonitoring="false" --namespace resource-locker-operator`

With the `enableMonitoring` flag set to false, I would expect the Helm chart not to try to create a `ServiceMonitor`, however I get the following error: `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`.

**Comment by raffaelespazzoli** [comment]
yeah, that feature has not be released. Please be patient, we are planning a release soon (next two weeks).

**Comment by raffaelespazzoli** [comment]
v1.0.8 contains the change

**Comment by Obirah** [comment]
Confirmed that it's working with v1.0.8
